// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NodeInfo.proto

package si.mlimedija.proto;

public final class NodeInfo {
  private NodeInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016NodeInfo.proto\"J\n\017NodeInfoRequest\022\016\n\006n" +
      "odeId\030\001 \001(\005\022\025\n\rnodeIpAddress\030\002 \001(\t\022\020\n\010no" +
      "dePort\030\003 \001(\005\"u\n\020NodeInfoResponse\022\016\n\006node" +
      "Id\030\001 \001(\005\022\021\n\tisHealthy\030\002 \001(\010\022\017\n\007mapSize\030\003" +
      " \001(\005\022\024\n\014responseCode\030\004 \001(\005\022\027\n\017responseMe" +
      "ssage\030\005 \001(\t2>\n\010nodeInfo\0222\n\013getNodeInfo\022\020" +
      ".NodeInfoRequest\032\021.NodeInfoResponseB\026\n\022s" +
      "i.mlimedija.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NodeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeInfoRequest_descriptor,
        new java.lang.String[] { "NodeId", "NodeIpAddress", "NodePort", });
    internal_static_NodeInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NodeInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeInfoResponse_descriptor,
        new java.lang.String[] { "NodeId", "IsHealthy", "MapSize", "ResponseCode", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
