// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NodeInfo.proto

package si.mlimedija.proto;

public interface NodeInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   */
  int getNodeId();

  /**
   * <code>string nodeIpAddress = 2;</code>
   */
  java.lang.String getNodeIpAddress();
  /**
   * <code>string nodeIpAddress = 2;</code>
   */
  com.google.protobuf.ByteString
      getNodeIpAddressBytes();
}
